import { OpportunityItem } from "@/types";

export const MOCK_OPPORTUNITIES: OpportunityItem[] = [
  {
    id: "opp_1",
    title: "Junior Software Engineer",
    company: "Nexus Systems",
    location: "San Francisco, CA (Hybrid)",
    employment_type: "Full-time",
    description: "Join our core web engineering team building Next.js and TypeScript SaaS platforms.",
    required_skills: ["React", "TypeScript", "Node.js", "Git Version Control", "REST API Design", "SQL & Relational DBs"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["React", "TypeScript", "Node.js", "Git Version Control", "REST API Design", "SQL & Relational DBs"],
    explanation: "Verify your skills to calculate personalized match score.",
    is_saved: false,
  },
  {
    id: "opp_2",
    title: "Full-Stack Developer",
    company: "Vortex AI",
    location: "Remote (US)",
    employment_type: "Full-time",
    description: "Build user-facing AI applications using Next.js, Supabase, and vector databases.",
    required_skills: ["Next.js", "TypeScript", "Tailwind CSS", "Python", "SQL & Relational DBs"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["Next.js", "TypeScript", "Tailwind CSS", "Python", "SQL & Relational DBs"],
    explanation: "Verify your skills to calculate personalized match score.",
    is_saved: false,
  },
  {
    id: "opp_3",
    title: "Data Analyst / Analytics Engineer",
    company: "CloudAnalytics Inc",
    location: "New York, NY (Remote)",
    employment_type: "Full-time",
    description: "Analyze product analytics telemetry, build SQL data pipelines, and design executive dashboards.",
    required_skills: ["SQL & Relational DBs", "Python", "STAR Behavioral Communication"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["SQL & Relational DBs", "Python", "STAR Behavioral Communication"],
    explanation: "Verify your skills to calculate personalized match score.",
    is_saved: false,
  },
  {
    id: "opp_4",
    title: "Product Associate",
    company: "Aura Labs",
    location: "Austin, TX (Hybrid)",
    employment_type: "Full-time",
    description: "Work with engineering leads and UI/UX designers to translate customer needs into product features.",
    required_skills: ["Agile / Scrum", "STAR Behavioral Communication"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["Agile / Scrum", "STAR Behavioral Communication"],
    explanation: "Verify your skills to calculate personalized match score.",
    is_saved: false,
  },
];
