import { OpportunityItem } from "@/types";

export const MOCK_OPPORTUNITIES: OpportunityItem[] = [
  // Cyber Security Roles
  {
    id: "opp_sec_1",
    title: "Cyber Security Analyst / SOC Specialist",
    company: "Cloudflare",
    location: "Austin, TX (Remote)",
    employment_type: "Full-time",
    description: "Monitor network traffic telemetry, perform SIEM incident response, and analyze security vulnerabilities.",
    required_skills: ["Cyber Security", "Wireshark", "SIEM", "SOC", "Network Security", "Kali Linux"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["Cyber Security", "Wireshark", "SIEM", "SOC", "Network Security", "Kali Linux"],
    explanation: "Upload or verify your resume skills to calculate your exact fit.",
    is_saved: false,
  },
  {
    id: "opp_sec_2",
    title: "Ethical Hacker / Penetration Tester",
    company: "Palo Alto Networks",
    location: "San Jose, CA (Hybrid)",
    employment_type: "Full-time",
    description: "Perform web application penetration testing, vulnerability assessments, and red team security simulations.",
    required_skills: ["Ethical Hacking", "Penetration Testing", "Kali Linux", "Burp Suite", "Metasploit", "Nmap", "OWASP"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["Ethical Hacking", "Penetration Testing", "Kali Linux", "Burp Suite", "Metasploit", "Nmap", "OWASP"],
    explanation: "Upload or verify your resume skills to calculate your exact fit.",
    is_saved: false,
  },

  // AI & Machine Learning Roles
  {
    id: "opp_ai_1",
    title: "Machine Learning Engineer",
    company: "Anthropic AI",
    location: "San Francisco, CA (Hybrid)",
    employment_type: "Full-time",
    description: "Train, fine-tune, and deploy large-scale ML models and deep learning pipelines in production.",
    required_skills: ["Python", "Machine Learning", "TensorFlow", "PyTorch", "Scikit-Learn", "Pandas", "NumPy"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["Python", "Machine Learning", "TensorFlow", "PyTorch", "Scikit-Learn", "Pandas", "NumPy"],
    explanation: "Upload or verify your resume skills to calculate your exact fit.",
    is_saved: false,
  },

  // Java & Backend Engineering Roles
  {
    id: "opp_java_1",
    title: "Java & Microservices Backend Developer",
    company: "Stripe",
    location: "New York, NY (Remote)",
    employment_type: "Full-time",
    description: "Design high-performance distributed payment systems using Java, Spring Boot, Microservices, and PostgreSQL.",
    required_skills: ["Java", "Spring Boot", "Microservices", "SQL", "PostgreSQL", "REST API", "Docker"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["Java", "Spring Boot", "Microservices", "SQL", "PostgreSQL", "REST API", "Docker"],
    explanation: "Upload or verify your resume skills to calculate your exact fit.",
    is_saved: false,
  },

  // Web Engineering Roles
  {
    id: "opp_web_1",
    title: "Frontend Developer (React & Next.js)",
    company: "Vercel",
    location: "San Francisco, CA (Remote)",
    employment_type: "Full-time",
    description: "Architect high-speed, serverless user interfaces and design systems using React, Next.js, and TypeScript.",
    required_skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "JavaScript", "Git"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "JavaScript", "Git"],
    explanation: "Upload or verify your resume skills to calculate your exact fit.",
    is_saved: false,
  },
  {
    id: "opp_web_2",
    title: "Full Stack Engineer",
    company: "Shopify",
    location: "Remote (US)",
    employment_type: "Full-time",
    description: "Develop scalable e-commerce infrastructure, GraphQL endpoints, and React frontend workflows.",
    required_skills: ["React", "Next.js", "Node.js", "TypeScript", "SQL", "Docker"],
    match_score: 0,
    matching_skills: [],
    missing_skills: ["React", "Next.js", "Node.js", "TypeScript", "SQL", "Docker"],
    explanation: "Upload or verify your resume skills to calculate your exact fit.",
    is_saved: false,
  },
];
